PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS blog (
    id INTEGER PRIMARY KEY NOT NULL,
    body TEXT NOT NULL,
    published BOOLEAN NOT NULL DEFAULT false,
    inserted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kayvee (
    key VARCHAR(64) PRIMARY KEY NOT NULL,
    value JSONB
);
