version: ""
name: "monolith"

services:
  overseer:
    build: .
    restart: unless-stopped
    ports:
      - 9900:9900
  
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monolith
    volumes:
      - pg_data:/var/lib/postgresql/data

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data